package com.example.backend.entities;

// The column is a plain varchar with no CHECK, so this list grows without a migration.
public enum ActivityAction {
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    ACCOUNT_REGISTERED,
    PERMISSION_DENIED,
    APPOINTMENT_BOOKED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_SESSIONS_ADDED,
    SESSION_SCHEDULED,
    // Kept for rows already written; new work names the status it moved to.
    SESSION_STATUS_CHANGED,
    SESSION_CANCELLED,
    SESSION_COMPLETED,
    SESSION_NO_SHOW,
    CLINICAL_PROFILE_UPDATED,

    // Account administration.
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_DELETED,
    ACCOUNT_STATUS_CHANGED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    PROFILE_UPDATED,
    PATIENT_REGISTERED_BY_STAFF,
    PATIENT_DEMOGRAPHICS_UPDATED,

    // Reads of clinical information.
    CLINICAL_PROFILE_VIEWED,
    CLINICAL_HISTORY_VIEWED,
    CLINICAL_LIST_VIEWED,
    SESSION_RECORDS_VIEWED,

    // Clinical record authorship.
    SESSION_RECORD_CREATED,
    SESSION_RECORD_AMENDED,

    // Security events beyond a plain failed login.
    ACCOUNT_LOCKED,
    AUTH_RATE_LIMITED,
    STALE_SESSION_REJECTED,
    ROLE_CHANGE_REJECTED,
    DISABLED_ACCOUNT_REJECTED,
    REFRESH_TOKEN_REJECTED,

    // Clinic configuration and catalogue.
    DOCTOR_CREATED,
    DOCTOR_UPDATED,
    DOCTOR_DELETED,
    AVAILABILITY_ADDED,
    AVAILABILITY_REMOVED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PATIENT_PRODUCT_ADDED,
    PATIENT_PRODUCT_DISCONTINUED,
    FORM_QUESTION_CREATED,
    FORM_QUESTION_UPDATED,
    FORM_QUESTION_ACTIVATED,
    FORM_QUESTION_DEACTIVATED
}
